name: Testing (MariaDB)

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      matrix:
        required: true
        type: string

jobs:
  filter:
    name: Filter Matrix
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.filter.outputs.matrix }}
    steps:
      - name: Filter incompatible combinations
        id: filter
        env:
          MATRIX: ${{ inputs.matrix }}
          VERSION: ${{ inputs.version }}
        run: |
          IFS='.' read -r major minor <<< "$VERSION"
          # Laravel 11.x requires MariaDB 10.10+
          if [[ $major -eq 10 && $minor -lt 10 ]]; then
            echo "matrix=$(echo "$MATRIX" | jq -c '[.[] | select(.laravel != "11.*")]')" >> "$GITHUB_OUTPUT"
          else
            echo "matrix=$(echo "$MATRIX" | jq -c .)" >> "$GITHUB_OUTPUT"
          fi

  test:
    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }}
    needs: filter

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.filter.outputs.matrix) }}

    services:
      database:
        image: mariadb:${{ inputs.version }}
        options: --health-cmd="healthcheck.sh --innodb_initialized" --health-interval=10s --health-timeout=5s --health-retries=3
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: pdo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: List Installed Dependencies
        run: composer show -D

      - name: Execute tests
        run: vendor/bin/pest
        env:
          DB_CONNECTION: ${{ matrix.laravel == '10.*' && 'mysql' || 'mariadb' }}
          DB_DATABASE: mysql
          DB_USERNAME: root
